language: java
os: linux
install: true
services:
  - docker

jdk:
  - openjdk13

script:
  - ./gradlew build --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - export IMAGE_NAME=docker.pkg.github.com/redasurc/tsmanager/ts-manager
  - "export IMAGE_VERSION=`./gradlew properties | grep ^version: | sed -e 's/version: //g'`"
  - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$IMAGE_VERSION; fi
  - docker push $IMAGE_NAME